CREATE TABLE Books (
                      id_books int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      person_id int REFERENCES Person(id_person) ON DELETE SET NULL
                      name varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL,

);

CREATE TABLE Person (
                        id_person int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fio varchar(100) NOT NULL UNIQUE,
                        yearofbirth int NOT NULL
);


